# Cow face ID

In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
# from sklearn.metrics import confusion_matrix
import itertools
import seaborn as sns
from random import randint
# imports for array-handling and plotting
import matplotlib
import os
# import tensorflow as tf
# from tensorflow.python.keras.layers import Input, Dense
%matplotlib inline

In [25]:
from PIL import Image
import numpy as np
import sys
import os
import csv

# load the original image
for file in os.listdir('data/05.08.22'):
    print(file)
    if file[-4:] == '.jpg':
        img_file = Image.open(f'data/05.08.22/{file}')
        # img_file.show()

        # get original image parameters...
        width, height = img_file.size
        format = img_file.format
        mode = img_file.mode

        # Make image Greyscale
        img_grey = img_file.convert('L')
        #img_grey.save('result.png')
        #img_grey.show()

        # Save Greyscale values
        value = np.asarray(img_grey.getdata(), dtype=int).reshape((img_grey.size[1], img_grey.size[0]))
        value = value.flatten()
        print(value)
        with open("img_pixels.csv", 'a') as f:
            writer = csv.writer(f)
            writer.writerow(value)

7acf2c89d2cfa72826a139940ba5c5ea.jpg
[137 137 137 ...  75  75  75]


/var/folders/vp/x2fg_x6j6g3g_jbsfc5y7c8r0000gn/T/ipykernel_8653/4156128074.py:25: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  value = np.asarray(img_grey.getdata(), dtype=np.int).reshape((img_grey.size[1], img_grey.size[0]))


435b7487f521cf5dc970a09a4409ca65.jpg
[129 129 129 ...  77  77  77]
b6d5cb4a93c4c2ac496e2e320ae50197.jpg
[145 147 147 ...  86  86  86]
3e4834e6649440c34b9ff41da75931a5.jpg
[171 152 163 ...  90  90  90]
ddef9b749cb04eabce07cc96fb53dc92.jpg
[166 153 158 ... 103 103 103]
924941a2b59f5ac207b9d79e361b0bae.jpg
[160 148 156 ...  81  81  81]
6c8b9baeaa157079667f5ff4aec5ba79.jpg
[134 128 123 ...  75  75  75]
3ce98b2f75fdb9643b3a85a6a3468b0e.jpg
[174 161 166 ...  86  86  86]
9fcdb61692bfca8679cdaebf36003394.jpg
[160 148 156 ...  91  91  91]
3503712989bdea2a10d271c7f1596881.jpg
[147 141 154 ...  81  80  78]
f47a7c67f6442ee33f3d80e20f41f951.jpg
[165 147 159 ...  81  81  81]
5e28160d90bb815429fe32c834b0b72f.jpg
[150 151 154 ...  77  77  77]
f555ecdcc242f74e1a13bf319419207c.jpg
[172 153 164 ...  53  57  60]
e4fb3819b44e80da00005dcf4c9d1c2c.jpg
[163 162 161 ...  86  86  86]
ae97d9a89da47a8eb40b656b6a17c484.jpg
[129 129 129 ...  70  70  70]
698cc4015cabc0057e8fdc387e0bea9d.jpg
[162 161 160 ...  89  89 